/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppWaConexaoRouteImport } from './routes/_app.wa-conexao'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppTelegramRouteImport } from './routes/_app.telegram'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServidoresRouteImport } from './routes/_app.servidores'
import { Route as AppRevendasRouteImport } from './routes/_app.revendas'
import { Route as AppResellerRouteImport } from './routes/_app.reseller'
import { Route as AppPostsRouteImport } from './routes/_app.posts'
import { Route as AppPlanosRouteImport } from './routes/_app.planos'
import { Route as AppPagamentosRouteImport } from './routes/_app.pagamentos'
import { Route as AppInstagramRouteImport } from './routes/_app.instagram'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppCreditosRouteImport } from './routes/_app.creditos'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'
import { Route as AppBroadcastRouteImport } from './routes/_app.broadcast'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAutomationRouteImport } from './routes/_app.automation'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAiChatRouteImport } from './routes/_app.ai-chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppWaConexaoRoute = AppWaConexaoRouteImport.update({
  id: '/wa-conexao',
  path: '/wa-conexao',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTelegramRoute = AppTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServidoresRoute = AppServidoresRouteImport.update({
  id: '/servidores',
  path: '/servidores',
  getParentRoute: () => AppRoute,
} as any)
const AppRevendasRoute = AppRevendasRouteImport.update({
  id: '/revendas',
  path: '/revendas',
  getParentRoute: () => AppRoute,
} as any)
const AppResellerRoute = AppResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsRoute = AppPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentosRoute = AppPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppInstagramRoute = AppInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditosRoute = AppCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastRoute = AppBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiChatRoute = AppAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-chat': typeof AppAiChatRoute
  '/analytics': typeof AppAnalyticsRoute
  '/automation': typeof AppAutomationRoute
  '/billing': typeof AppBillingRoute
  '/broadcast': typeof AppBroadcastRoute
  '/categorias': typeof AppCategoriasRoute
  '/creditos': typeof AppCreditosRoute
  '/crm': typeof AppCrmRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/instagram': typeof AppInstagramRoute
  '/pagamentos': typeof AppPagamentosRoute
  '/planos': typeof AppPlanosRoute
  '/posts': typeof AppPostsRoute
  '/reseller': typeof AppResellerRoute
  '/revendas': typeof AppRevendasRoute
  '/servidores': typeof AppServidoresRoute
  '/settings': typeof AppSettingsRoute
  '/telegram': typeof AppTelegramRoute
  '/templates': typeof AppTemplatesRoute
  '/wa-conexao': typeof AppWaConexaoRoute
  '/whatsapp': typeof AppWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-chat': typeof AppAiChatRoute
  '/analytics': typeof AppAnalyticsRoute
  '/automation': typeof AppAutomationRoute
  '/billing': typeof AppBillingRoute
  '/broadcast': typeof AppBroadcastRoute
  '/categorias': typeof AppCategoriasRoute
  '/creditos': typeof AppCreditosRoute
  '/crm': typeof AppCrmRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/instagram': typeof AppInstagramRoute
  '/pagamentos': typeof AppPagamentosRoute
  '/planos': typeof AppPlanosRoute
  '/posts': typeof AppPostsRoute
  '/reseller': typeof AppResellerRoute
  '/revendas': typeof AppRevendasRoute
  '/servidores': typeof AppServidoresRoute
  '/settings': typeof AppSettingsRoute
  '/telegram': typeof AppTelegramRoute
  '/templates': typeof AppTemplatesRoute
  '/wa-conexao': typeof AppWaConexaoRoute
  '/whatsapp': typeof AppWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai-chat': typeof AppAiChatRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/automation': typeof AppAutomationRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/broadcast': typeof AppBroadcastRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/creditos': typeof AppCreditosRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/instagram': typeof AppInstagramRoute
  '/_app/pagamentos': typeof AppPagamentosRoute
  '/_app/planos': typeof AppPlanosRoute
  '/_app/posts': typeof AppPostsRoute
  '/_app/reseller': typeof AppResellerRoute
  '/_app/revendas': typeof AppRevendasRoute
  '/_app/servidores': typeof AppServidoresRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/telegram': typeof AppTelegramRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/wa-conexao': typeof AppWaConexaoRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-chat'
    | '/analytics'
    | '/automation'
    | '/billing'
    | '/broadcast'
    | '/categorias'
    | '/creditos'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/instagram'
    | '/pagamentos'
    | '/planos'
    | '/posts'
    | '/reseller'
    | '/revendas'
    | '/servidores'
    | '/settings'
    | '/telegram'
    | '/templates'
    | '/wa-conexao'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-chat'
    | '/analytics'
    | '/automation'
    | '/billing'
    | '/broadcast'
    | '/categorias'
    | '/creditos'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/instagram'
    | '/pagamentos'
    | '/planos'
    | '/posts'
    | '/reseller'
    | '/revendas'
    | '/servidores'
    | '/settings'
    | '/telegram'
    | '/templates'
    | '/wa-conexao'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ai-chat'
    | '/_app/analytics'
    | '/_app/automation'
    | '/_app/billing'
    | '/_app/broadcast'
    | '/_app/categorias'
    | '/_app/creditos'
    | '/_app/crm'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/instagram'
    | '/_app/pagamentos'
    | '/_app/planos'
    | '/_app/posts'
    | '/_app/reseller'
    | '/_app/revendas'
    | '/_app/servidores'
    | '/_app/settings'
    | '/_app/telegram'
    | '/_app/templates'
    | '/_app/wa-conexao'
    | '/_app/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wa-conexao': {
      id: '/_app/wa-conexao'
      path: '/wa-conexao'
      fullPath: '/wa-conexao'
      preLoaderRoute: typeof AppWaConexaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/telegram': {
      id: '/_app/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof AppTelegramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servidores': {
      id: '/_app/servidores'
      path: '/servidores'
      fullPath: '/servidores'
      preLoaderRoute: typeof AppServidoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revendas': {
      id: '/_app/revendas'
      path: '/revendas'
      fullPath: '/revendas'
      preLoaderRoute: typeof AppRevendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reseller': {
      id: '/_app/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof AppResellerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts': {
      id: '/_app/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AppPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos': {
      id: '/_app/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pagamentos': {
      id: '/_app/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AppPagamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instagram': {
      id: '/_app/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AppInstagramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creditos': {
      id: '/_app/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AppCreditosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcast': {
      id: '/_app/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AppBroadcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation': {
      id: '/_app/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-chat': {
      id: '/_app/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AppAiChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiChatRoute: typeof AppAiChatRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAutomationRoute: typeof AppAutomationRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBroadcastRoute: typeof AppBroadcastRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppCreditosRoute: typeof AppCreditosRoute
  AppCrmRoute: typeof AppCrmRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInstagramRoute: typeof AppInstagramRoute
  AppPagamentosRoute: typeof AppPagamentosRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppPostsRoute: typeof AppPostsRoute
  AppResellerRoute: typeof AppResellerRoute
  AppRevendasRoute: typeof AppRevendasRoute
  AppServidoresRoute: typeof AppServidoresRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTelegramRoute: typeof AppTelegramRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppWaConexaoRoute: typeof AppWaConexaoRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiChatRoute: AppAiChatRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAutomationRoute: AppAutomationRoute,
  AppBillingRoute: AppBillingRoute,
  AppBroadcastRoute: AppBroadcastRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppCreditosRoute: AppCreditosRoute,
  AppCrmRoute: AppCrmRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInstagramRoute: AppInstagramRoute,
  AppPagamentosRoute: AppPagamentosRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppPostsRoute: AppPostsRoute,
  AppResellerRoute: AppResellerRoute,
  AppRevendasRoute: AppRevendasRoute,
  AppServidoresRoute: AppServidoresRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTelegramRoute: AppTelegramRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppWaConexaoRoute: AppWaConexaoRoute,
  AppWhatsappRoute: AppWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
