/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppTelegramRouteImport } from './routes/_app.telegram'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResellerRouteImport } from './routes/_app.reseller'
import { Route as AppInstagramRouteImport } from './routes/_app.instagram'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAutomationRouteImport } from './routes/_app.automation'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAiChatRouteImport } from './routes/_app.ai-chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppTelegramRoute = AppTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResellerRoute = AppResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => AppRoute,
} as any)
const AppInstagramRoute = AppInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiChatRoute = AppAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-chat': typeof AppAiChatRoute
  '/analytics': typeof AppAnalyticsRoute
  '/automation': typeof AppAutomationRoute
  '/billing': typeof AppBillingRoute
  '/crm': typeof AppCrmRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/instagram': typeof AppInstagramRoute
  '/reseller': typeof AppResellerRoute
  '/settings': typeof AppSettingsRoute
  '/telegram': typeof AppTelegramRoute
  '/whatsapp': typeof AppWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-chat': typeof AppAiChatRoute
  '/analytics': typeof AppAnalyticsRoute
  '/automation': typeof AppAutomationRoute
  '/billing': typeof AppBillingRoute
  '/crm': typeof AppCrmRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/instagram': typeof AppInstagramRoute
  '/reseller': typeof AppResellerRoute
  '/settings': typeof AppSettingsRoute
  '/telegram': typeof AppTelegramRoute
  '/whatsapp': typeof AppWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai-chat': typeof AppAiChatRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/automation': typeof AppAutomationRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/instagram': typeof AppInstagramRoute
  '/_app/reseller': typeof AppResellerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/telegram': typeof AppTelegramRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-chat'
    | '/analytics'
    | '/automation'
    | '/billing'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/instagram'
    | '/reseller'
    | '/settings'
    | '/telegram'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-chat'
    | '/analytics'
    | '/automation'
    | '/billing'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/instagram'
    | '/reseller'
    | '/settings'
    | '/telegram'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ai-chat'
    | '/_app/analytics'
    | '/_app/automation'
    | '/_app/billing'
    | '/_app/crm'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/instagram'
    | '/_app/reseller'
    | '/_app/settings'
    | '/_app/telegram'
    | '/_app/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/telegram': {
      id: '/_app/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof AppTelegramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reseller': {
      id: '/_app/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof AppResellerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instagram': {
      id: '/_app/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AppInstagramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation': {
      id: '/_app/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-chat': {
      id: '/_app/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AppAiChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiChatRoute: typeof AppAiChatRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAutomationRoute: typeof AppAutomationRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCrmRoute: typeof AppCrmRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInstagramRoute: typeof AppInstagramRoute
  AppResellerRoute: typeof AppResellerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTelegramRoute: typeof AppTelegramRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiChatRoute: AppAiChatRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAutomationRoute: AppAutomationRoute,
  AppBillingRoute: AppBillingRoute,
  AppCrmRoute: AppCrmRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInstagramRoute: AppInstagramRoute,
  AppResellerRoute: AppResellerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTelegramRoute: AppTelegramRoute,
  AppWhatsappRoute: AppWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
